DROP DATABASE IF EXISTS bank;
CREATE DATABASE bank;
USE bank;

DROP TABLE IF EXISTS branch;
CREATE TABLE branch(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(15),
	City VARCHAR(15)
) AUTO_INCREMENT=1;

DROP TABLE IF EXISTS manager;
CREATE TABLE manager(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	BranchID INT,
	FName VARCHAR(15),
	LName VARCHAR(15),
  CONSTRAINT fk_manager_branch FOREIGN KEY (BranchID) REFERENCES branch(ID)
) AUTO_INCREMENT=1;

DROP TABLE IF EXISTS employee;
CREATE TABLE employee (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	FName VARCHAR(15),
	LName VARCHAR(15),
	ManagerID INT,
	CONSTRAINT fk_emp_manager FOREIGN KEY (ManagerID) REFERENCES manager(ID)
) AUTO_INCREMENT=1;

DROP TABLE IF EXISTS customer;
CREATE TABLE customer (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	FName VARCHAR(15),
	LName VARCHAR(15),
	Street VARCHAR(15),
	City VARCHAR(15),
	EmployeeAssignedID INT,
	CONSTRAINT fk_employee FOREIGN KEY (EmployeeAssignedID) REFERENCES employee(ID)	
) AUTO_INCREMENT=1;

DROP TABLE IF EXISTS account;
CREATE TABLE account (
	AccountNumber INT UNIQUE,
	AccountType VARCHAR(1),
	BranchID INT,
	CustomerID INT,
	Balance INT,
	CONSTRAINT fk_acc_branch FOREIGN KEY (BranchID) REFERENCES branch(ID),
	CONSTRAINT fk_customerID FOREIGN KEY (CustomerID) REFERENCES customer(ID)
);END;



